weatherApiEncodingKey : 3FZCxvPHQygrXcCm2MEXJU57MJOngj9Gn0IAo6WO8qlVBwIdkkqeFjR2ckhoiMvr%2Braz5xBVwUd9Po72sBy3JQ%3D%3D
weatherApiDecodingKey : 3FZCxvPHQygrXcCm2MEXJU57MJOngj9Gn0IAo6WO8qlVBwIdkkqeFjR2ckhoiMvr+raz5xBVwUd9Po72sBy3JQ==
