spring:
  #민감정보
  config:
    location: classpath:/naver-cloud-config.yml
  #DB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/meoku #로컬개발
    url: jdbc:mariadb://mariadb:3306/meoku #운영
    username: root
    password: admin12
  # JPA
  jpa:
    hibernate:
      # create : entity를 drop cascade 하고 다시 생성
      # update : entity가 수정되면 수정된 내용만 반영
      # create-drop,validate, none
      # 하이버네이트가 자동으로 생성해주는 DDL은 신뢰성이 떨어지기 때문에
      # 절대로! 운영DB 환경에서 그대로 사용하면 안되고, 직접 DDL을 작성하는 것을 권장
       ddl-auto: none
    properties: # Additional native properties to set on the JPA provider.
      hibernate:
        show-sql: true                  # System.out 으로 출력
        format_sql: true                 # 로그, 콘솔의 SQL을 좀 더 이쁘게 출력합니다.
        highlight_sql: true             # SQL 출력을 ANSI escape codes를 사용하여 색을 부여합니다.
        #use_sql_comments: true          # 보다 쉬운 디버깅을 위해 SQL 내부에 /* */의 주석을 추가합니다.

  # Logging
  logging:
    level: # 각 package 별로 로깅 레벨을 지정할 수 있다.
      org.hibernate.type: trace                   # 콘솔차에 조건에 바인딩되는 값 및 조회 결과 출력
      org.hibernate.SQL: DEBUG                    # logger를 통해 하이버네이트 실행 SQL
      org.hibernate.type.descriptor.sql: trace    # sql의 ? 값을 Parameter로 보여줌.
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE