naver_ocr_url : https://z1rz5md7j1.apigw.ntruss.com/custom/v1/24920/eeaadf091eda056fb5306227ca52673c631fbf63f597ad4999fdaf0f6c8e23ef/infer
naver_api_scret_key : Qkh6WXhHRGxKdG5IdkNhdXhFUUFtYXl2b2hUR1VOU0g=
TEMPLATEIDS : 29995